name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Pipeline démarré avec succès !"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST scan
        run: semgrep scan --config p/security-audit --sarif --output semgrep.sarif juice-shop
        continue-on-error: true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
