name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Pipeline démarré avec succès !"
